### ISSUE TITLE
[RFE] Deleted messages support

### ISSUE THREAD

**Issue by biswasab** [tulir/mautrix-telegram#302]
It will be awesome if we get deleted message support across bridge. As per my knowledge riot can delete message and so does Telegram. Is there a way to bridge this?

**Comment by tulir** [comment]
They're already bridged, but sometimes telegram doesn't feel like telling the bridge about deletions

**Comment by biswasab** [comment]
@tulir Interesting, That's why. I actually tested it and found that deleting messages has no effect on the matrix side.

**Comment by tulir** [comment]
Make sure the bridge bot has permissions to redact messages. Telegram doesn't tell who deleted a message, so the redactions go through the bridge bot.

**Comment by biswasab** [comment]
@tulir Thanks. Closing.

**Comment by opk12** [comment]
> Make sure the bridge bot has permissions to redact messages. Telegram doesn't tell who deleted a message, so the redactions go through the bridge bot.

@tulir Is it technically possible that the redaction goes through the author of the message? In other words, regardless of who deleted on Telegram, Matrix sees a user deleting her own message. Kicks and bans would translate to the fake user just leaving the room.

The purpose is that the bot would not need higher privilege (which we are not granting in some OpenStreetMap communities, due to historical episodes some time ago, where the bot randomly kicked people out of the room).
