### ISSUE TITLE
Convert webp files to png broken

### ISSUE THREAD

**Issue by enko** [tulir/mautrix-telegram#307]
This seems to be a regression for #18. The [code](https://github.com/tulir/mautrix-telegram/blob/master/mautrix_telegram/util/file_transfer.py#L194) seems fine, but that was only from a precursory look.

This is what I recieved from my wife:

```
{
  "type": "m.sticker",
  "content": {
    "url": "mxc://schumacher.im/xQsqnmrPgOmRyWVDbvmYDcDF",
    "body": "🐸 (frog face)",
    "info": {
      "size": 88626,
      "mimetype": "image/webp",
      "w": 228,
      "h": 256
    },
    "m.relates_to": null
  }
}
```

I would expect it, that the sticker is converted to a png, because Riot on iOS does not support webp (though I have opened an issue https://github.com/vector-im/riot-ios/issues/2353).

**Comment by tulir** [comment]
Looks like the conversion is fine, but the mime type in the event content is `image/webp` instead of `image/png`. The image in that event is a PNG if you download it: https://matrix.schumacher.im/_matrix/media/v1/download/schumacher.im/xQsqnmrPgOmRyWVDbvmYDcDF

I think the problem with that is that the telegram document -> matrix file info conversion [code](https://github.com/tulir/mautrix-telegram/blob/master/mautrix_telegram/portal.py#L1389) prefers the telegram document mime type instead of the reuploaded file metadata mime type

**Comment by enko** [comment]
Thanks for fixing!
