### ISSUE TITLE
(Feature request) option to forward messages only in one direction (from matrix to telegram), to co-exist with telegram-irc bridges

### ISSUE THREAD

**Issue by 2fchar** [tulir/mautrix-telegram#313]
There are irc channels and telegram chats already bridged, where all irc users appear as one user on telegram and vice-versa.

Matrix users can join such channels via irc, but can't enjoy the full benefit of a matrix-telegram bridge. Adding `mautrix-telegram` to such channels would be great.

Because telegram bots can't see each other, there aren't any risk of creating loops. And irc messages will only be sent to matrix directly, and won't go through telegram, so they don't appear twice on matrix.

But messages sent from matrix to irc would be forwarded to telegram, if they were to be forwarded by `mautrix-telegram`, they would appear twice on telegram.

The best option would be having all messages go through matrix, but existing infrastructure isn't usually easy to change. So I guess this is an easy way to make incremental changes.

**Comment by tulir** [comment]
If I understood correctly, you want to disable the Telegram->Matrix part, so basically

![image](https://user-images.githubusercontent.com/4224639/56567054-c67f4f80-65bc-11e9-9caf-d65300424cae.png)

I don't really see the point, since as you said,

> But messages sent from matrix to irc would be forwarded to telegram, if they were to be forwarded by mautrix-telegram, they would appear twice on telegram.

If you change existing infrastructure and disable IRC->Telegram bridging, then you may as well remove that bridge altogether.

**Comment by olmari** [comment]
I'm also agains't this, but thing that could be beneficial (wit hall bridges) would be federation in bridges themselves, would solve this issue too, among some others, if done right...
