### ISSUE TITLE
Initially only creates rooms for group chats, not 1-1 chats

### ISSUE THREAD

**Issue by julianuu** [tulir/mautrix-telegram#360]
After a telegram user messages me the room is created though. In riot I can also only find telegram contacts that are in said groups chats, and not all my telegram contacts

**Comment by tulir** [comment]
This is intentional, see https://github.com/tulir/mautrix-telegram/wiki/Creating-and-managing-chats for info on how to open portals.

As for syncing the contact users into Matrix before they're in any portal, that'll probably happen when I add an option to create a community (for filtering) containing your portals and contacts.
