### ISSUE TITLE
Automate migrating Telegram bridge user to other instance with keeping old rooms and history

### ISSUE THREAD

**Issue by MurzNN** [tulir/mautrix-telegram#394]
At now migration process from one bridge instance to other is not so comfortable: new bridge will create new separate room for each contact and group, and chat history will kept on old rooms, so user will got 2 rooms for each contact - first is dead but with history, second is active, but without history. After next migration user will got 3 duplicated rooms, etc. But if user make logout from old instance (instead of shutting off bridge instance) - it will be kicked from rooms and lost all history.

This problem stops me (and, I think, many other users) from moving from overloaded `@telegram:t2bot.io` to same instance on other server.

For solve this problem will be good to implement some migration process, something like `!tg migrate @telegram:newserver.org` command, that will invite new bot to all rooms, managed for this user on old server, transfer to him needed permissions in each room and other needed info. 

What do you think about this idea?

**Comment by tulir** [comment]
This probably isn't going to happen:

* For private chats, you'll be able to backfill history
* For group chats that you don't own:
  * If there are no other matrix users, you can just backfill history
  * If there are other matrix users, the bridge can't just break the room for the other users because one user wants to move away
* For group chats that you do own, you can already `!tg unbridge` and re-bridge with a different bridge.

**Comment by MurzNN** [comment]
As workaround, this can be implemented via posting `m.room.tombstone` events, or maybe something better will be provided in [MSC2923: Connect Matrix room to another Matrix room](https://github.com/matrix-org/matrix-doc/pull/2923)

**Comment by MadLittleMods** [comment]
Also related to https://github.com/matrix-org/matrix-doc/pull/2716
